### GET request to example server
GET http://127.0.0.1:8080/api/teams/user/
    ?generated-in=IntelliJ IDEA

###
POST http://127.0.0.1:8080/api/teams
Content-Type: application/json
Accept: application/json

{
  "name": "새로운 그룹",
  "projectName": "팀 생성 프로젝트",
  "description": "팀을 생성한다.",
  "creatorId": 1
}
###
POST http://127.0.0.1:8080/api/teams/invite
Content-Type: application/json
Accept: application/json

